### ISSUE TITLE
I am quite interesting in this project, and please let me involved.

### ISSUE THREAD

**Issue by kcauchy** [TreeNote/TreeNote#1]
There are no public members in this project. So I don't know whom to ask.

I want to create a HTML 5/Canvas or WebGL based tree view task management online like trello. I think that is very suitable for IT task managements. Aslo I am interesting in doing some development on devices.

Let's discuss our ideas. To my knowledgement, few task management products provide the dependencies tree functions.

**Comment by Tamriel** [comment]
Thanks for your interest :)
My motiviation for this project was to built a mature tree-like task-manager for linux. The collaboration function can be used for shared projects, for brainstorming together or for building something like a wiki in a small group. However, my main focus lies in personal use right now. 

What are your ideas (functions, mockup) for project management online like trello?

I did not plan to develop smartphone or web app versions of TreeNote, but it is perfectly possible if someone want to do this. However, an Android port may be quite easy with Qt.

How have you found my project?

**Comment by kcauchy** [comment]
Basically, our ideas might be the same:

1. Tree displaying
2. Tasks has dependencies.
3. You can close the tasks if you want.

What I intend to do is a little bit complicated than yours:
1. It is a website like wrike and trello, we can have desktop or mobile clients, but not important.
2. It has a complex support for multi-users: permissions, task assignment, code base integration and so on.
3. Every task shall have a history.
4. Every task is independent. You can add a references to some other task that own by others.
5. Every task have branches. Branches are independent basically, and they are working in a concurrent mode.

For me, there are hundreds of items on trello, and create a new board is quite difficult, since you have to add new administrators, etc. And tasks have no dependencies, no history, no status etc.

If you are a supervisor, you can see tasks like this:
```
Tasks - Tree Node Website
    - Task: Website  [Own by kcauchy]                 (0%)              [Expand]
    - Task: Desktop Python Client [Own by Tamriel]   (50%)              [Expand]
```
Supervising is easy. Since you can supervising tasks on a specific level. If you a project manager, you see all root tasks; If you a programmer, you can focus on some specific bugs.

If you open the first task:

```
    - Task: Website [Own by kcauchy]                             (0%)              
         - Concurrent Groups
               - Design
                   - Task: Architecture Design  [Own by kcauchy] (0%)
                   - Task: UI Design [Own by kcauchy]            (0%)
               - Demo
                   - Task: Desktop Demo [Own by kcauchy]         (0%)
                         - commits  abcdef123  Simple text was made.
```

The `Concurrent Groups` is not good displaying in text mode. Since we can make two lists on the screen, one left, one right, which means the task has `two branches`, if we use `Canvas` or `WebGL` or `GDI` or `DirectX` or `OpenGL` or `Cocoa`.

Tha's ba

**Comment by Tamriel** [comment]
I like your ideas very much! I am not sure if we should merge the two products 'information management' and 'project management'. I think it's not too difficult to implement your ideas in the Qt + Python client. Then, all the tree structure editing functions are already present. However, you said a desktop client has little priority, so starting an own project may be easier.

**Comment by kcauchy** [comment]
My idea, however, it is too large.

At the beginning, we should just focus on task management. If you just make a desktop client, then how can you allow multiply users?

My idea is the front-end and server are separated,  a Qt + Python client is welcomed.

There are too many details need to be discussed if we decided to start the server based Tree Management system.

**Comment by Tamriel** [comment]
Right now, my application is like http://etherpad.org/. All user have the same rights, there is no logic on the server. The server is just there to have a shared database.

**Comment by kcauchy** [comment]
I am not good at Qt or Python. 

Well, your product is suitable for small groups, and I think I can help you if you are willing to let me get involved. A shared server maybe I can help. (Or maybe you don't need server)

Also, if you want my help, you need to change your license to MIT-liked, since I am willing to make further development based on your work.

What is your roadmap? Can you share it with the TreeNote?

**Comment by Tamriel** [comment]
I have a server, thanks :)
I believe in libre software. However, we need to earn money somehow. Maybe https://snowdrift.coop/p/snowdrift/w/en/intro will guide the way. For now, I like the idea of a capable and extensible knowledge manager for everyone, thus free and cross-platform.
Do you still want to help? ;)

**Comment by kcauchy** [comment]
We have different ideas to open source. I believed the GNU is the best solution when I was younger, but now I feel like, free is not that important to an open source project.

However, money is. If Redhat doesn't make enough money, Linux can't be so good nowadays.  This one is based on GNU.

But, there are also so many projects not based on GNU. Like apache, nginx, spark, node, openssl, etc. They are so good because there are people willing to pay for it.

Nowadays, an excellent idea means nothing. We need to do things right. If we can do things right, why others use "a copy" of us? That makes no sense.

Definitely we need to make money.

Maybe I misunderstand your target, yours is "knowledge management", and my target is "task management".

If your target is task management, I believe the guys who pay for us, are the companies, which means we need permission system, and web-based. (Like how github, wrike, and trello make money) 

Again, you can still use a client, the core thing is the product is good enough.

**Comment by kcauchy** [comment]
I do have my ideas, also I want to get involved and help you somehow under your roadmap and instructions and code standards and testing standards.

**Comment by Tamriel** [comment]
I think the advantages of web-based are:
#1 copy urls
#2 copy text
#3 accesible from all devices
I think #1 and #2 are very easily implemented in my rich client. #3 is not that important.
Therefore we could use my existing code.

However, I am still studying and have little time. I want to set my focus on improving TreeNote, before doing a new product. Thanks for your interest. If, how would you want to proceed?
