### ISSUE TITLE
Checkbox "Hide done tasks"

### ISSUE THREAD

**Issue by Tamriel** [TreeNote/TreeNote#17]

**Comment by senpl** [comment]
how this is done ??

**Comment by Tamriel** [comment]
Pressing the blue button in the top right opens the side bars.
At the right side bar setting the drop down menu *type* to *todo* insert the search string *t=todo* into the search bar. This will show only todo items.

Sadly, I try to avoid the search / filter function, since for very huge trees (like my tree) it is utterly slow.

Someday I will continue working on a complete rewrite of TreeNote.
Here is the prototype I wrote in Scala.js: https://treenote.org/demo

**Comment by Tamriel** [comment]
Pressing the blue button in the top right opens the side bars.
At the right side bar setting the drop down menu *type* to *todo* insert the search string *t=todo* into the search bar. This will show only todo items.

Sadly, I try to avoid the search / filter function, since for very huge trees (like my tree) it is utterly slow.

Someday I will continue working on a complete rewrite of TreeNote.
Here is the prototype I wrote in Scala.js: https://treenote.org/demo
