### ISSUE TITLE
Pressing tab twice breaks keyboard navigation

### ISSUE THREAD

**Issue by The-Compiler** [TreeNote/TreeNote#27]
When doing tab twice on an entry to edit it and stop editing, keyboard navigation like up/down is broken. Works again after clicking on an element.

**Comment by Tamriel** [comment]
I know the origin of this behaviour and will fix this.
You can workaround by showing all columns (shift+C or View -> Hide / show columns).

**Comment by Tamriel** [comment]
Fixed :)
