### ISSUE TITLE
W and S (move item up or down) doesn't seem to work in v1.7 Windows 7 64 bit

### ISSUE THREAD

**Issue by ejlmljt** [TreeNote/TreeNote#31]
A and D move item left and right but W and S do not move item up or down.  W and S work in v1.6  I have installed on the same computer

**Comment by Tamriel** [comment]
Yes you are right. I will fix it next week at max.

**Comment by ejlmljt** [comment]
Thanks Jan

**Comment by Tamriel** [comment]
Ok, it is a [bug](http://stackoverflow.com/questions/41680808/qtableview-no-longer-showing-rows-since-update-to-5-7-1) in PyQt 5.7.1. On my machine it worked, since I used PyQt 5.7.2.
I will create a new version when PyQt 5.7.2. is released in pip.

**Comment by Tamriel** [comment]
I was tired of waiting, so I coded a simple workaround. I published a new version with a working windows release: http://treenote.org/download/

**Comment by Tamriel** [comment]
Unfortunately the workaround introduced some crashes.
Fortunately yesterday was a new PyQt version released, which fixed all the issues :)
So I did another release... http://treenote.org/download/
