### ISSUE TITLE
Provide documetation/wiki or document existing features

### ISSUE THREAD

**Issue by senpl** [TreeNote/TreeNote#48]
Provided german link is not easly accessed from public. Providing wiki for this project would allow users to document their functions/usage etc. Currently no documentation is provided and project ite is no longer avaliable. Thing like eg. search syntax would be nice to document.

**Comment by Tamriel** [comment]
The documentation is the example tree in the application. The german version of the tree is an almost complete explanation of the features. I could insert an auto-translated version of that tree into the readme file.

**Comment by JonasDralle** [comment]
i feel like that's ill documentation anyways.
How about pasting he example tree into a GitHub wiki or using [gh-pages](https://pages.github.com/)?

**Comment by Tamriel** [comment]
I think the english manual is complete.
Apart from in the app, you can read it here: [https://github.com/TreeNote/TreeNote/wiki](https://github.com/TreeNote/TreeNote/wiki)
Feel free to extend it.
